"""add timestamps to career

Revision ID: 4b024091c198
Revises: 1db042e7c363
Create Date: 2026-03-17 14:09:02.654558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b024091c198'
down_revision = '1db042e7c363'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('careers', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('careers', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('careers', 'updated_at')
    op.drop_column('careers', 'created_at')
    # ### end Alembic commands ###
